### ISSUE TITLE
Custom build and environment update?

### ISSUE THREAD

**Issue by Hideman85** [serverlesspub/latex-aws-lambda-layer#4]
Hi I just want to build it with additional latex package and upgrade to node10x or node12x AWS environment since node8.10 is deprecated.

I would like to ensure that import, svg and graphics latex packages will be compiled.

**Comment by gojko** [comment]
you should be able to configure that that in https://github.com/serverlesspub/latex-aws-lambda-layer/blob/master/texlive.profile

**Comment by Hideman85** [comment]
And for node environment?
Currently I have trouble using it in node 10 or 12 so I still use it in node8.10

**Comment by Hideman85** [comment]
I don't understand how the texlive.profile works. https://www.tug.org/texlive/doc/install-tl.html#PROFILES
How should I specify that I want svg, graphics and import packages?

**Comment by Hideman85** [comment]
Okey found it
